version: '3.9'

services:
  frontend:
    build:
      context: ./CrediConsultaWeb
    ports:
      - "${FRONTEND_PORT:-4200}:80"
    depends_on:
      - backend
    networks:
      - rede-app

  backend:
    build:
      context: ./credito-consulta-api
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DB_PASS}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_SERVERS}
    depends_on:
      - db
      - kafka
    networks:
      - rede-app

  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - rede-app

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "${ZOOKEEPER_PORT:-2181}:2181"
    networks:
      - rede-app

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - rede-app

networks:
  rede-app:
    driver: bridge
